site_name: HelloRIC Documentation

# TODO: Add basic section about kobuki-drivers
nav:
  - Home: index.md
  - User Interface: '!import https://helloric:${EMOTION_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/ui/emotion.git?branch=main&multi_docs=True'
  - AI:
    - LLM: '!import https://helloric:${LLM_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/ros_llm.git?branch=main&multi_docs=True'
    - Speech to Text: '!import https://helloric:${STT_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/ros_stt.git?branch=main&multi_docs=True'
    - Text to Speech: '!import https://helloric:${TTS_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/ros_tts.git?branch=main&multi_docs=True'
    - Chat: '!import https://helloric:${CHAT_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/ros_chat.git?branch=main&multi_docs=True'
  - Tour:
    - Tour Manager UI: '!import https://helloric:${TOUR_MANAGER_UI_TOKEN}@git.hb.dfki.de/helloric/base/tour-manager-ui.git?branch=main&multi_docs=True'
    - Tour Persistence: '!import https://helloric:${PERSISTENCE_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/tour_persistence_node.git?branch=main&multi_docs=True'
    - MapDesc Persistence: '!import https://helloric:${MAPDESC_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/mapdesc_persistence.git?branch=main&multi_docs=True'
    - MongoDB: '!import https://helloric:${MONGO_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/mongodb_server.git?branch=main&multi_docs=True'
  - HelloRIC UI COM: '!import https://helloric:${HELLORIC_UI_COM_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/helloric_ui_com.git?branch=main&multi_docs=True'
  - Hardware:
    - E-Plan: '!import https://helloric:${E_PLAN_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/hardware/e-plan.git?branch=main&multi_docs=True'
    - Rollen: '!import https://helloric:${ROLLEN_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/hardware/rollen.git?branch=main&multi_docs=True'
    - Baseplate: '!import https://helloric:${BASEPLATE_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/hardware/baseplate.git?branch=main&multi_docs=True'
    - Aussenshell: '!import https://helloric:${AUSSENSHELL_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/hardware/ausenshell-und-rollen.git?branch=main&multi_docs=True'
  - Navigation: '!import https://helloric:${NAVIGATION_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-24/navigation/ricbot-simulation.git?branch=main&extra_imports=["docs/assets/*"]&multi_docs=True'
  - Zenoh Router: '!import https://helloric:${ZENOH_ROUTER_PROJECT_TOKEN}@git.hb.dfki.de/helloric/helloric-25/software/zenoh_router?branch=main&multi_docs=True'

theme:
  logo: assets/logo.png
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox
  - mermaid2
  - macros
  - mkdocstrings:
        handlers:
          python:
            paths:
              - temp_dir/llm-server/src
              - temp_dir/ricbot-simulation/src
  - multirepo:
      cleanup: false
      keep_docs_dir: true

extra:
  version:
    provider: mike
