[project]
name = "helloric-doc"
version = "0.1.0"
requires-python = "~=3.12.10,<3.13,>=3.9"
dependencies = [
    "mkdocs-glightbox>=0.4.0",
    "mkdocs-material>=9.6.14",
    "mkdocs-multirepo-plugin>=0.8.3",
    "mkdocstrings[python]>=0.29.1",
]
