name: ci 
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: uv pip install git+https://helloric:${{ secrets.LLM_PROJECT_TOKEN }}@git.hb.dfki.de/helloric/helloric-25/software/language-model@dev --no-deps
        env:
          GIT_LFS_SKIP_SMUDGE: 1
      - run: envsubst < mkdocs.yml > tmp.yml && rm mkdocs.yml && mv tmp.yml mkdocs.yml && uv run mkdocs gh-deploy --force
        env:
          EMOTION_PROJECT_TOKEN: ${{ secrets.EMOTION_PROJECT_TOKEN }}
          LLM_PROJECT_TOKEN: ${{ secrets.LLM_PROJECT_TOKEN }}
          NAVIGATION_PROJECT_TOKEN: ${{ secrets.NAVIGATION_PROJECT_TOKEN }}
          STT_PROJECT_TOKEN: ${{ secrets.STT_PROJECT_TOKEN }}
          GIT_LFS_SKIP_SMUDGE: 1
